name: textbook

channels:
  - conda-forge

dependencies:
  - ruby
  - pip:
    - bs4
    - tqdm
    - notebook
    - numpy
    - datascience
    - pyyaml
    - nbformat
    - nbclean
    - nbgitpuller
    - -r ./binder/requirements.txt
